Agent:
  type: object
  config:
    description: "An Agent"
    fields:
      id:
        type: "Int!"
        description: "The unique ID of the agent."
      firstname:
        type: "String!"
      lastname:
        type: "String!"
        access: "@=isAuthenticated()"
      birthDate:
        type: "Date"
#        access: "@=isAuthenticated()"
      email:
        type: "[String]"
#        access: "@=isAuthenticated()"

