AgentInput:
  type: "input-object"
  config:
    fields:
      lastname:
        type: "String!"
      firstname:
        type: "String!"
      birthdate:
        type: "DateTime"
      email:
        type: "String"
