Date:
  type: custom-scalar
  config:
    serialize: ["App\\Type\\DateType", "serialize"]
    parseValue: ["App\\Type\\DateType", "parseValue"]
    parseLiteral: ["App\\Type\\DateType", "parseLiteral"]

